force-app/main/default/objects/Permission_Set_Grant__c/Permission_Set_Grant__c.object-meta.xml
<CustomObject>
    <label>Permission Set Grant</label>
    <nameField>
        <displayFormat>PSG-{000000}</displayFormat>
        <label>Permission Set Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Set Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>8</defaultValue>
    <label>Duration</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Duration_Unit__c.field-meta.xml
<CustomField>
    <fullName>Duration_Unit__c</fullName>
    <label>Duration Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Granted__c.field-meta.xml
<CustomField>
    <fullName>Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Permission_Set_Id__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Id__c</fullName>
    <externalId>true</externalId>
    <label>Permission Set Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users allowed.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Set_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PermissionSetGrantMgrController.cls
public class PermissionSetGrantMgrController
{
    @AuraEnabled
    public static List<PSWrapper> getPermissionSets(Id userId)
    {
        List<PermissionSet> permSets = [SELECT Name, LicenseId, License.Name, Label FROM PermissionSet WHERE IsOwnedByProfile = FALSE ORDER BY Name ASC];
        Map<Id, PSWrapper> wrappersByPermSetId = new Map<Id, PSWrapper>();
        for(PermissionSet ps: permSets)
        {
            wrappersByPermSetId.put(ps.Id, new PSWrapper(ps));
        }
        if(String.isBlank(userId))
        {
            return wrappersByPermSetId.values();
        }
        else 
        {
            User u = [SELECT Profile.UserLicenseId FROM User WHERE Id = :userId];
            List<PermissionSetAssignment> existingPSA = [SELECT PermissionSetId, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId = :userId];
            Set<Id> alreadyAssignedPSIds = new Set<Id>();
            for(PermissionSetAssignment psa: existingPSA)
            {
                alreadyAssignedPSIds.add(psa.PermissionSetId);
            }
            for(PermissionSet ps: permSets)
            {
                if(!String.isBlank(ps.LicenseId) && u.Profile.UserLicenseId != ps.LicenseId)
                {
                    PSWrapper psWrap = wrappersByPermSetId.get(ps.Id);
                    psWrap.disabled = 'true';
                    psWrap.displayText += ' - User does not match required License Type: ' + ps.License.Name;
                }
                else if(alreadyAssignedPSIds.contains(ps.Id))
                {
                    PSWrapper psWrap = wrappersByPermSetId.get(ps.Id);
                    psWrap.disabled = 'true';
                    psWrap.displayText += ' - already assigned to user';
                }
            }
            return wrappersByPermSetId.values();
        }
    }

    @AuraEnabled
    public static Permission_Set_Grant__c insertPermSetGrant(Id userId, Id permSetId, Decimal dur, String durUnit)
    {
        Permission_Set_Grant__c psg = new Permission_Set_Grant__c(User__c = userId, Permission_Set_Id__c = permSetId, Duration__c = dur, Duration_Unit__c = durUnit, Granted__c = TRUE);
        insert psg;
        return psg;
    }

    public class PSWrapper
    {
        @AuraEnabled public PermissionSet permSet;
        @AuraEnabled public String disabled;
        @AuraEnabled public String displayText;
        @AuraEnabled public String permSetId;

        public PSWrapper(PermissionSet permSet)
        {
            this.permSet = permSet;
            this.disabled = 'false';
            this.displayText = permSet.Label;
            this.permSetId = permSet.Id;
        }
    }
}