force-app/main/default/objects/Permission_Set_Grant__c/Permission_Set_Grant__c.object-meta.xml
<CustomObject>
    <label>Permission Set Grant</label>
    <nameField>
        <displayFormat>PSG-{000000}</displayFormat>
        <label>Permission Set Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Set Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Permission_Set_Id__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Id__c</fullName>
    <externalId>true</externalId>
    <label>Permission Set Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users allowed.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Set_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PermissionSetGrantTest.cls
@isTest private with sharing class PermissionSetGrantTest
{
    static PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Name = 'TestPermissionSet'];
    static User u = [SELECT Id FROM User WHERE IsActive = TRUE AND Profile.UserLicense.Name = 'Salesforce' LIMIT 1];

    @isTest private static void grantPermissionSet()
    {
        Permission_Set_Grant__c psg = new Permission_Set_Grant__c(User__c = u.Id, Permission_Set_Id__c = permSet.Id);
        PermissionSetGrantInvocable.GrantInfo gi = new PermissionSetGrantInvocable.GrantInfo();
        gi.grant = psg;
        gi.status = 'Granted';
        Test.startTest();
            PermissionSetGrantInvocable.managePermSetGrant(new List<PermissionSetGrantInvocable.GrantInfo>{gi});
        Test.stopTest();

        List<PermissionSetAssignment> permSetAssigned = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :u.Id AND PermissionSetId = :permSet.Id];
        System.assertEquals(1, permSetAssigned.size());
    }

    @isTest private static void removePermissionSet()
    {
        Permission_Set_Grant__c psg = new Permission_Set_Grant__c(User__c = u.Id, Permission_Set_Id__c = permSet.Id);
        PermissionSetGrantInvocable.GrantInfo gi = new PermissionSetGrantInvocable.GrantInfo();
        gi.grant = psg;
        gi.status = 'Expired';
        Test.startTest();
            PermissionSetGrantInvocable.managePermSetGrant(new List<PermissionSetGrantInvocable.GrantInfo>{gi});
        Test.stopTest();

        List<PermissionSetAssignment> permSetRemoved = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :u.Id AND PermissionSetId = :permSet.Id];
        System.assertEquals(0, permSetRemoved.size());    
    }
}