force-app/main/default/objects/Permission_Set_Grant__c/Permission_Set_Grant__c.object-meta.xml
<CustomObject>
    <label>Permission Set Grant</label>
    <nameField>
        <displayFormat>PSG-{000000}</displayFormat>
        <label>Permission Set Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Set Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission_Set_Grant__c/fields/Permission_Set_Id__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Id__c</fullName>
    <externalId>true</externalId>
    <label>Permission Set Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission_Set_Grant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users allowed.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Set_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PermissionSetGrantInvocable.cls
public class PermissionSetGrantInvocable
{
    public class GrantInfo
    {
        @InvocableVariable(required=TRUE) public Permission_Set_Grant__c grant;
        @InvocableVariable(required=TRUE) public String status;
    }

    @InvocableMethod(Label='GrantPermissionSet')
    public static void managePermSetGrant(List<GrantInfo> grantInfo)
    {
        System.enqueueJob(new PermissionSetGrantQueuable(grantInfo[0]));
    }

    private class PermissionSetGrantQueuable implements Queueable
    {
        private GrantInfo grant;

        public PermissionSetGrantQueuable(GrantInfo grant)
        {
            this.grant = grant;
        }

        public void execute(QueueableContext qc)
        {
            List<PermissionSetAssignment> existingPermSetAssgn = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :grant.grant.User__c AND PermissionSetId = :grant.grant.Permission_Set_Id__c];

            if(grant.status == 'Granted' && existingPermSetAssgn.isEmpty()) {
                insert new PermissionSetAssignment(AssigneeId = grant.grant.User__c, PermissionSetId = grant.grant.Permission_Set_Id__c);
            } else if(grant.status == 'Expired' && !existingPermSetAssgn.isEmpty()){
                delete existingPermSetAssgn;
            }
        }
    }
}